export const userChooseTypes = {
    ADD_USER_CHOOSE: "ADD_USER_CHOOSE",
    REMOVE_USER_CHOOSE: "REMOVE_USER_CHOOSE",
    CLEAR_USER_CHOOSE: "CLEAR_USER_CHOOSE",
    ADD_USER_INPUT: "ADD_USER_INPUT"
  };
  